// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqN63JtZtsJSjU7wQWLy65DFxakduCXpc',
    appId: '1:807771854341:web:4df588d32cb05d01d1ae6c',
    messagingSenderId: '807771854341',
    projectId: 'realtime-laugh',
    authDomain: 'realtime-laugh.firebaseapp.com',
    storageBucket: 'realtime-laugh.firebasestorage.app',
    measurementId: 'G-95Z3KY2F49',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBek7fhUfB-VMzefnk3c9swr-4GGUfuZEg',
    appId: '1:807771854341:android:c0e98ee27ae49e26d1ae6c',
    messagingSenderId: '807771854341',
    projectId: 'realtime-laugh',
    storageBucket: 'realtime-laugh.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGe28vWODCXIFjc23K_drZrbODEWqt69c',
    appId: '1:807771854341:ios:b5bff392dc4ebc9ad1ae6c',
    messagingSenderId: '807771854341',
    projectId: 'realtime-laugh',
    storageBucket: 'realtime-laugh.firebasestorage.app',
    iosBundleId: 'com.example.realitimeLaugh',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGe28vWODCXIFjc23K_drZrbODEWqt69c',
    appId: '1:807771854341:ios:b5bff392dc4ebc9ad1ae6c',
    messagingSenderId: '807771854341',
    projectId: 'realtime-laugh',
    storageBucket: 'realtime-laugh.firebasestorage.app',
    iosBundleId: 'com.example.realitimeLaugh',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqN63JtZtsJSjU7wQWLy65DFxakduCXpc',
    appId: '1:807771854341:web:6a00333d10f201a6d1ae6c',
    messagingSenderId: '807771854341',
    projectId: 'realtime-laugh',
    authDomain: 'realtime-laugh.firebaseapp.com',
    storageBucket: 'realtime-laugh.firebasestorage.app',
    measurementId: 'G-83F2VB8CJ5',
  );

}